# Filename: config.yaml
# Description: Contains configuration variables for navigation project
# Author: Thomas Wood (odell.wood@gmail.com)

# Parameters for the Unity Environment
Environment:
  # location of executable
  Filepath: ./Tennis_Linux_NoVis/Tennis.x86_64
  Success: 0.5          # score success cutoff
  # Location of ml-agents python directory.
  Unity_pythonpath: /home/thomas/code/ml-agents-0.4.0b/python
  Random_seed: 123        # random seed passed to all RNGs involved in code.

Policy:
  fc1_size: 128  # size of the first hidden layer in the policy network
  fc2_size: 128  # size of the second hidden layer in the policy network
